# Generated by Django 2.0.3 on 2018-03-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180320_0042'),
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='projects',
            field=models.ManyToManyField(to='accounts.Project'),
        ),
    ]
