# Generated by Django 2.0.2 on 2018-03-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
