# Generated by Django 2.0.3 on 2018-03-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180320_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='user',
        ),
        migrations.DeleteModel(
            name='supervisor',
        ),
    ]
