# Generated by Django 2.0.3 on 2018-03-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180320_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='user',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employees',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
