# Generated by Django 2.0.3 on 2018-03-23 19:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180321_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='emp_name',
            field=models.CharField(default=accounts.models.Profile, max_length=100),
        ),
    ]
