# Generated by Django 2.0.3 on 2018-03-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180323_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='project_name',
            field=models.CharField(default='project_name', max_length=100),
        ),
    ]
