# Generated by Django 2.0.3 on 2018-03-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_timesheet_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='project_name',
        ),
    ]
